source 'https://rubygems.org'

gem 'active_model_serializers'
gem 'acts_as_list'
gem 'angular_rails_csrf'
gem 'annotate'
gem 'bootstrap-sass'
gem 'bourbon'
gem 'carrierwave'
gem 'ckeditor', github: 'gambala/ckeditor'
gem 'coffee-rails'
gem 'enum_help'
gem 'enumerize'
gem 'figaro'
gem 'font-awesome-rails'
gem 'friendly_id'
gem 'gon'
gem 'jquery-rails'
gem 'jquery-slick-rails'
gem 'jquery-turbolinks'
gem 'kaminari'
gem 'mandrill_mailer'
gem 'mini_magick'
gem 'ngannotate-rails'
gem 'nokogiri' # premailer dependency
gem 'pg'
gem 'premailer-rails'
gem 'pry'
gem 'pry-rails'
gem 'rails', '4.2.4'
gem 'rollbar'
gem 'russian'
gem 'sassc-rails'
gem 'sidekiq'
gem 'sitemap_generator'
gem 'slim'
gem 'sorcery'
gem 'turbolinks', github: 'rails/turbolinks'
gem 'uglifier'
gem 'underscore-rails'
gem 'unicorn', group: :production

group :development, :test do
  gem 'factory_girl'
  gem 'parallel_tests'
  gem 'rspec-rails'
  gem 'spring'
  gem 'spring-commands-rspec'
end

group :development do
  gem 'bullet'
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-figaro-yml'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'capistrano-sidekiq'
  gem 'capistrano-unicorn-nginx'
  gem 'guard', require: false
  gem 'guard-bundler', require: false
  gem 'guard-livereload', require: false
  gem 'guard-passenger', github: 'beverlyguillermo/guard-passenger', require: false
  gem 'guard-rspec', require: false
  gem 'letter_opener'
  gem 'meta_request'
  gem 'passenger'
  gem 'rack-livereload'
  gem 'web-console'
end

source 'https://rails-assets.org' do
  gem 'rails-assets-angular'
  gem 'rails-assets-angular-animate'
  gem 'rails-assets-angular-auto-focus'
  gem 'rails-assets-angular-i18n'
  gem 'rails-assets-angular-ladda'
  gem 'rails-assets-angular-sanitize'
  gem 'rails-assets-angular-ui-bootstrap-bower'
  gem 'rails-assets-angular-ui-router'
  gem 'rails-assets-angular-ui-router-title'
  gem 'rails-assets-angular-xeditable'
  gem 'rails-assets-autofill-event'
  gem 'rails-assets-breakpoint-sass'
  gem 'rails-assets-cferdinandi--smooth-scroll'
  gem 'rails-assets-ink'
  gem 'rails-assets-jasny-bootstrap'
  gem 'rails-assets-jquery.inputmask'
  gem 'rails-assets-ladda'
  gem 'rails-assets-lodash'
  gem 'rails-assets-masonry'
  gem 'rails-assets-ng-ckeditor'
  gem 'rails-assets-normalize-css'
  gem 'rails-assets-restangular'
  gem 'rails-assets-selectize'
  gem 'rails-assets-Sortable'
end
