server '95.213.195.242', user: 'deployer', port: 3501, roles: %w(web app db)
set :forbidden_locations, ['/88.php',
                           '/cms/',
                           '^/.bzr',
                           '^/.git',
                           '^/.hg',
                           '^/.svn',
                           '^/_admin',
                           '^/aaa',
                           '^/adm/',
                           '^/admin/login.php',
                           '^/administrator',
                           '^/ajax.php',
                           '^/apple-app-site-association',
                           '^/away',
                           '^/backup',
                           '^/bitrix',
                           '^/browserconfig.xml',
                           '^/cache',
                           '^/cgi-sys',
                           '^/clientaccesspolicy',
                           '^/core/',
                           '^/data/',
                           '^/default.php',
                           '^/downloader',
                           '^/engine',
                           '^/error_log.php',
                           '^/go/',
                           '^/hostcmsfiles',
                           '^/html/logs.php',
                           '^/include/ajax',
                           '^/includes/init.php',
                           '^/index.php',
                           '^/installed',
                           '^/js/',
                           '^/license.php',
                           '^/m/',
                           '^/manager',
                           '^/media/system',
                           '^/mobile',
                           '^/modules/system',
                           '^/mysql',
                           '^/netcat',
                           '^/password_double_opt',
                           '^/phpmyadmin',
                           '^/privacy.php',
                           '^/redirect.php',
                           '^/scripts/init.js',
                           '^/sftp-settings',
                           '^/skin',
                           '^/sql',
                           '^/styles/skins',
                           '^/templates/system',
                           '^/typo3',
                           '^/uploads/goods',
                           '^/wp-admin',
                           '^/wp-content',
                           '^/wp-login.php',
                           '^/xml/',
                           '^/xml1-wp2.php',
                           '^/xmlrpc.php']
set :nginx_config_name, 'default'
set :nginx_server_name, '95.213.195.242'
set :ssh_options, keys: %w(/home/gambala/.ssh/id_rsa),
                  forward_agent: false,
                  auth_methods: %w(publickey)
