server 'www.vpzven.ru', user: 'deployer', port: 3501, roles: %w(web app db)
set :forbidden_locations, ['/88.php',
                           '/.bzr',
                           '/.git',
                           '/.hg',
                           '/.svn',
                           '/_admin',
                           '/aaa',
                           '/adm',
                           '/admin/login.php',
                           '/administrator',
                           '/apple-app-site-association',
                           '/away',
                           '/backup',
                           '/bitrix',
                           '/cache',
                           '/cgi-sys',
                           '/clientaccesspolicy',
                           '/cms',
                           '/core',
                           '/default.php',
                           '/downloader',
                           '/engine',
                           '/go',
                           '/hostcmsfiles',
                           '/html/logs.php',
                           '/images/cms/admin',
                           '/include/ajax',
                           '/includes/init.php',
                           '/installed',
                           '/js',
                           '/license.php',
                           '/m',
                           '/manager',
                           '/media/system',
                           '/mobile',
                           '/modules/system',
                           '/mysql',
                           '/netcat',
                           '/password_double_opt',
                           '/phpmyadmin',
                           '/redirect.php',
                           '/scripts/init.js',
                           '/sftp-settings',
                           '/skin',
                           '/sql',
                           '/styles/skins',
                           '/templates/system',
                           '/typo3',
                           '/wp-admin',
                           '/wp-login.php',
                           '/xml',
                           '/xmlrpc.php']
set :nginx_server_name, 'www.vpzven.ru'
set :ssh_options, keys: %w(/home/gambala/.ssh/id_rsa),
                  forward_agent: false,
                  auth_methods: %w(publickey)
